In [66]:
from tensorflow.keras.preprocessing.text import one_hot


In [67]:
### sentences
sent = ['the glass of milk',
        'the glass of juice',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good'
        ]

In [68]:
## Define the vocabulary size
voc_size=10000

In [69]:
### One Hot Representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[2419, 9069, 6372, 8389],
 [2419, 9069, 6372, 7592],
 [9114, 5776, 6753, 1302, 7753],
 [9114, 5776, 6753, 1302, 4902],
 [5364, 2419, 1445, 6372, 1326],
 [1890, 1604, 7626, 1302]]

In [70]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [71]:
sent_length = 8
embeded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embeded_docs)

[[   0    0    0    0 2419 9069 6372 8389]
 [   0    0    0    0 2419 9069 6372 7592]
 [   0    0    0 9114 5776 6753 1302 7753]
 [   0    0    0 9114 5776 6753 1302 4902]
 [   0    0    0 5364 2419 1445 6372 1326]
 [   0    0    0    0 1890 1604 7626 1302]]


In [72]:
## Feature representation
dim=10


In [ ]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')


c:\Users\sharma011\Documents\aiml\code\Learning Project With Simple RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [74]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [75]:
model.predict(embeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 284ms/step


array([[[ 0.00249463, -0.04384119, -0.04709532, -0.03626442,
          0.0214396 ,  0.00717098, -0.02909855, -0.02460796,
          0.01534953, -0.02005924],
        [ 0.00249463, -0.04384119, -0.04709532, -0.03626442,
          0.0214396 ,  0.00717098, -0.02909855, -0.02460796,
          0.01534953, -0.02005924],
        [ 0.00249463, -0.04384119, -0.04709532, -0.03626442,
          0.0214396 ,  0.00717098, -0.02909855, -0.02460796,
          0.01534953, -0.02005924],
        [ 0.00249463, -0.04384119, -0.04709532, -0.03626442,
          0.0214396 ,  0.00717098, -0.02909855, -0.02460796,
          0.01534953, -0.02005924],
        [-0.01223568, -0.0013295 , -0.04822529,  0.01330725,
          0.02197341, -0.01885525,  0.0277651 ,  0.04469519,
          0.01926542, -0.03362633],
        [-0.02537831, -0.00471453, -0.03736019, -0.041957  ,
         -0.04171882,  0.03541479, -0.02805376, -0.01327121,
         -0.01936403,  0.02259754],
        [-0.0477312 ,  0.02938446, -0.043973  , -0.0

In [76]:
embeded_docs[0]

array([   0,    0,    0,    0, 2419, 9069, 6372, 8389], dtype=int32)

In [77]:
model.predict(embeded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>